server:
  port: 8762

spring:
  application:
    name: api-gateway

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}-${random.int}
    hostname: localhost

zuul:
  #  ignored-services: *
  prefix: /api
  routes:
    jpaDate:
      path: /jpa-date/**
      serviceId: jpa-date
#    allocationService:
#      path: /allocation-service/**
#      serviceId: allocation-service